# Generated by Django 5.0.6 on 2024-06-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='duracion',
            field=models.IntegerField(verbose_name='Duracion del curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.TextField(verbose_name='Nombre del cursos'),
        ),
    ]
